--- #YAML:1.0
name:                Compress-Raw-Bzip2
version:             2.009
abstract:            Low-Level Interface to bzip2 compression library
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
